# Generated by Django 3.0.7 on 2021-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210103_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('fiction', 'Fiction'), ('novels', 'Novels')], default='regular', max_length=20, verbose_name='Book Type'),
        ),
    ]
