# Generated by Django 3.0.7 on 2021-01-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210102_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='Pages'),
        ),
    ]
