# Generated by Django 3.0.7 on 2021-01-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='book_type',
        ),
    ]
