# Generated by Django 3.0.7 on 2021-01-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210104_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='flat_days_charge',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=15, verbose_name='Flat Days Charge'),
        ),
    ]
