# Generated by Django 3.0.7 on 2021-01-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_per_book',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=15, verbose_name='Order Cost'),
        ),
    ]
